commands = {
'\\widetilde{ac}', '\\overgroup{AB}', '\\utilde{AB}', '\\undergroup{AB}', '\\acute{a}',
'\\vec{F}', '\\Overrightarrow{AB}', '\\bar{y}', '\\overleftarrow{AB}', '\\overrightarrow{AB}',
'\\breve{a}', '\\underleftarrow{AB}', '\\underrightarrow{AB}', '\\check{a}', '\\overleftharpoon{ac}',
'\\overrightharpoon{ac}', '\\dot{a}', '\\overleftrightarrow{AB}', '\\overbrace{AB}', '\\ddot{a}',
'\\underleftrightarrow{AB}', '\\underbrace{AB}', '\\grave{a}', '\\overlinesegment{AB}', '\\hat{\\theta}',
'\\underlinesegment{AB}', '\\widehat{ac}', '\\widecheck{ac}', '\\`{a}', '\\^{a}',
'\\|', '\\lvert', '\\lang', '\\left(\\LARGE{AB}\\right)', '\\big(',
'\\Big(', '\\bigg(', '\\Bigg(', '\\left', '\\middle',
'\\right', '\\Bigg', '\\begin{matrix}', '\\begin{pmatrix}', '\\begin{vmatrix}',
'\\begin{Bmatrix}', 'x = \\begin{cases}', '\\begin{smallmatrix}', '\\begin{equation}', '\\begin{gather}',
'\\begin{CD}', '\\\\', '\\tag', '\\href{https:/', '\\url{https:/',
'\\includegraphics', '\\html', '\\varepsilon', '\\varpi', '\\digamma',
'\\imath', '\\jmath', '\\aleph', '\\alef', '\\alefsym',
'\\beth', '\\gimel', '\\daleth', '\\eth', '\\char',
'\\cancel{5}', '\\overbrace{a+b+c}^{\\text{note}}', '\\bcancel{5}', '\\underbrace{a+b+c}_{\\text{note}}', '\\xcancel{ABC}',
'\\sout{abc}', '$a_{\\angl n}', '\\phase{-78^\\circ}', '\\tag{hi} x+y^{2x}', '\\tag*{hi} x+y^{2x}',
'\\nobreak', '\\sum_{\\substack{0&lt,i&lt,m\\\\0&lt,j&lt,n}}', '\\raisebox', '\\vcenter', '{=}\\mathllap{/',
'\\mathrlap{\\,/', '\\sqrt{\\smash[b]{y}}', '\\sum_{\\mathclap{1\\le i\\le j\\le n}} x_{ij}', '\\llap', '\\thinspace',
'\\&gt,', '\\medspace', '\\thickspace', '\\enspace', '\\quad',
'\\qquad', '\\&lt,space&gt,', '\\nobreakspace', '\\space', '\\kern',
'\\mkern', '\\forall', '\\exists', '\\exist', '\\nexists',
'\\in', '\\isin', '\\notin', '\\def\\foo{x^2} \\foo + \\foo', '\\gdef\\bar#1{#1^2} \\bar{y} + \\bar{y}',
'\\edef\\macroname#1#2…{definition to be expanded}', '\\xdef\\macroname#1#2…{definition to be expanded}', '\\let\\foo=\\bar', '\\futurelet\\foo\\bar x', '\\global\\def\\macroname#1#2…{definition}',
'\\newcommand\\macroname[numargs]{definition}', '\\renewcommand\\macroname[numargs]{definition}', '\\providecommand\\macroname[numargs]{definition}', '\\gdef', '\\par',
'\\char', '\\makeatletter', '\\sum', '\\int', '\\iint',
'\\iiint', '\\oint', '\\oiint', '\\oiiint', '\\amalg',
'\\And', '\\ast', '\\barwedge', '\\bigcirc', '\\bmod',
'\\boxdot', '\\boxminus', '\\boxplus', '\\boxtimes', '\\bullet',
'\\Cap', '\\cap', '\\frac{a}{b}', '\\arcsin', '\\arccos',
'\\arctan', '\\arctg', '\\arcctg', '\\arg', '\\ch',
'\\cos', '\\operatorname{f}', '\\argmax', '\\varinjlim', '\\argmin',
'\\det', '\\gcd', '\\varprojlim', '\\inf', '\\operatorname*{f}',
'\\limits', '\\sqrt{x}', '\\sqrt[3]{x}', '\\stackrel{!}{=}', '\\approx',
'\\approxcolon', '\\approxcoloncolon', '\\approxeq', '\\asymp', '\\backepsilon',
'\\backsim', '\\backsimeq', '\\between', '\\bowtie', '\\bumpeq',
'\\Bumpeq', '\\circeq', '\\colonapprox', '\\Colonapprox', '\\coloneq',
'\\Coloneq', '\\coloneqq', '\\Coloneqq', '\\colonsim', '\\Colonsim',
'\\cong', '\\curlyeqprec', '\\curlyeqsucc', '\\dashv', '\\dblcolon',
'\\doteq', '\\Doteq', '\\not =', '\\gnapprox', '\\gneq',
'\\gneqq', '\\gnsim', '\\gvertneqq', '\\lnapprox', '\\lneq',
'\\lneqq', '\\lnsim', '\\lvertneqq', '\\ncong', '\\ne',
'\\neq', '\\ngeq', '\\ngeqq', '\\circlearrowleft', '\\circlearrowright',
'\\curvearrowleft', '\\curvearrowright', '\\Darr', '\\dArr', '\\darr',
'\\dashleftarrow', '\\dashrightarrow', '\\downarrow', '\\Downarrow', '\\downdownarrows',
'\\downharpoonleft', '\\downharpoonright', '\\gets', '\\Harr', '\\hArr',
'\\harr', '\\hookleftarrow', '\\hookrightarrow', '\\iff', '\\impliedby',
'\\implies', '\\Larr', '\\lArr', '\\larr', '\\leadsto',
'\\leftarrow', '\\Leftarrow', '\\leftarrowtail', '\\leftharpoondown', '\\xleftarrow{abc}',
'\\xrightarrow[under]{over}', '\\xLeftarrow{abc}', '\\xRightarrow{abc}', '\\xleftrightarrow{abc}', '\\xLeftrightarrow{abc}',
'\\xhookleftarrow{abc}', '\\xhookrightarrow{abc}', '\\xtwoheadleftarrow{abc}', '\\xtwoheadrightarrow{abc}', '\\xleftharpoonup{abc}',
'\\xrightharpoonup{abc}', '\\xleftharpoondown{abc}', '\\xrightharpoondown{abc}', '\\xleftrightharpoons{abc}', '\\xrightleftharpoons{abc}',
'\\xtofrom{abc}', '\\xmapsto{abc}', '\\xlongequal{abc}', '\\xrightarrow[under]{over}', '\\bra{\\phi}',
'\\Bra{\\phi}', '\\mathbin', '\\mathopen', '\\color{blue} F=ma', '\\color',
'\\textcolor{blue}{F=ma}', '\\textcolor{#228B22}{F=ma}', '\\colorbox{aqua}{$F=ma$}', '\\fcolorbox{red}{aqua}{$F=ma$}', '\\colorbox',
'\\mathrm{Ab0}', '\\mathnormal{Ab0}', '\\textrm{Ab0}', '\\rm Ab0', '\\textnormal{Ab0}',
'\\text{Ab0}', '\\mathsf{Ab0}', '\\textsf{Ab0}', '\\sf Ab0', '\\tt Ab0',
'\\mathscr{AB}', '\\textXX', '\\pmb', '\\Huge AB', '\\huge AB',
'\\LARGE AB', '\\Large AB', '\\large AB', '\\displaystyle\\sum_{i=1}^n', '\\textstyle\\sum_{i=1}^n',
'\\scriptstyle x', '\\scriptscriptstyle x', '\\lim\\limits_x', '\\lim\\nolimits_x', '\\verb!x^2!',
'\\text{…}', '\\%', '\\#', '\\&amp,', '\\_',
'\\text{\\textunderscore}', '\\text{--}', '\\text{\\textendash}', '\\text{---}', '\\text{\\textemdash}',
'\\text{\\textasciitilde}', '\\text{\\textasciicircum}', '\\lq', '\\text{\\textquoteright}', '\\rq',
'\\text{\\textquotedblleft}', '\\text{\\textquotedblright}', '\\colon', '\\backprime', '\\prime',
'\\text{\\textless}', '\\text{\\textgreater}', '\\text{\\textbar}', '\\text{\\textbardbl}', '\\text{\\textbraceleft}',
'\\text{\\textbraceright}', '\\text{\\textbackslash}', '\\text{\\P}', '\\text{\\S}', '\\text{\\sect}',
'\\copyright', '\\circledR', '\\text{\\textregistered}', '\\circledS', '\\text{\\textcircled a}'
}

output = {}
for i, w in ipairs(commands) do
  output[i] = {word = w; label = w; insertText = w; filterText = w}
end
return output
