commands = {
'n!',
'a\\!b',
'\\def\\bar#1{#1^2} \\bar{y}',
'\\#',
'%',
'\\%',
'\\begin{matrix} a & b\\cr c & d \\end{matrix}',
'\\&',
"'",
"\\text{\\'{a}}",
'(',
')',
'\\text{\\(\\frac a b\\)}',
'a\\ b',
'\\text{\\"{a}}',
'\\text{\\textdollar}',
'a\\,\\,{b}',
'\\text{\\.{a}}',
'a\\:\\:{b}',
'a\\;\\;{b}',
'x_i',
'\\_',
'\\text{\\`{a}}',
'<',
'\\text{\\={a}}',
'>',
'a\\>\\>{b}',
'[',
']',
'{a}',
'{a}',
'\\{',
'\\}',
'\\vert',
'\\Vert',
'\\text{no~no~no~breaks}',
'\\text{\\~{a}}',
'\\begin{matrix} a & b\\\\ c & d\\end{matrix}',
'x^i',
'\\text{\\^{a}}',
'\\text{\\AA}',
'\\text{\\aa}',
'{a \\above{2pt} b+1}',
'\\abovewithdelims',
'\\acute e',
'\\text{\\AE}',
'\\text{\\ae}',
'\\alef',
'\\alefsym',
'\\aleph',
'\\begin{align}a&=b+c\\\\d+e&=f\\end{align}',
'\\begin{align*}a&=b+c\\\\d+e&=f\\end{align*}',
'\\begin{aligned}a&=b+c\\\\d+e&=f\\end{aligned}',
'\\begin{alignat}{2}10&x+&3&y=2\\\\3&x+&13&y=4\\end{alignat}',
'\\begin{alignat*}{2}10&x+&3&y=2\\\\3&x+&13&y=4\\end{alignat*}',
'\\begin{alignedat}{2}10&x+&3&y=2\\\\3&x+&13&y=4\\end{alignedat}',
'\\allowbreak',
'\\Alpha',
'\\alpha',
'\\amalg',
'\\And',
'\\and',
'\\ang',
'a_{\\angl n}',
'a_\\angln',
'\\angle',
'\\approx',
'\\approxeq',
'\\approxcolon',
'\\approxcoloncolon',
'\\arccos',
'\\arcctg',
'\\arcsin',
'\\arctan',
'\\arctg',
'\\arg',
'\\argmax',
'\\argmin',
'\\begin{array}{cc}a&b\\\\c&d\\end{array}',
'\\array',
'\\def\\arraystretch{1.5}\\begin{array}{cc}a&b\\\\c&d\\end{array}',
'\\Arrowvert',
'\\arrowvert',
'\\ast',
'\\asymp',
'{a \\atop b}',
'\\atopwithdelims',
'\\backepsilon',
'\\backprime',
'\\backsim',
'\\backsimeq',
'\\backslash',
'\\bar{y}',
'\\barwedge',
'\\Bbb{ABC}',
'\\Bbbk',
'\\bbox',
'\\bcancel{5}',
'\\because',
'\\begin{matrix} a & b\\\\ c & d\\end{matrix}',
'\\begingroup',
'\\Beta',
'\\beta',
'\\beth',
'\\between',
'\\bf AaBb12',
'\\bfseries',
'\\big(\\big)',
'\\Big(\\Big)',
'\\bigcap',
'\\bigcirc',
'\\bigcup',
'\\bigg(\\bigg)',
'\\Bigg(\\Bigg)',
'\\biggl(',
'\\Biggl(',
'\\biggm\\vert',
'\\Biggm\\vert',
'\\biggr)',
'\\Biggr)',
'\\bigl(',
'\\Bigl(',
'\\bigm\\vert',
'\\Bigm\\vert',
'\\bigodot',
'\\bigominus',
'\\bigoplus',
'\\bigoslash',
'\\bigotimes',
'\\bigr)',
'\\Bigr)',
'\\bigsqcap',
'\\bigsqcup',
'\\bigstar',
'\\bigtriangledown',
'\\bigtriangleup',
'\\biguplus',
'\\bigvee',
'\\bigwedge',
'\\binom n k',
'\\blacklozenge',
'\\blacksquare',
'\\blacktriangle',
'\\blacktriangledown',
'\\blacktriangleleft',
'\\blacktriangleright',
'\\bm{AaBb}',
'\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}',
'\\begin{Bmatrix*}[r]0&-1\\\\-1&0\\end{Bmatrix*}',
'\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}',
'\\begin{bmatrix*}[r]0&-1\\\\-1&0\\end{bmatrix*}',
'a \\bmod b',
'\\bold{AaBb123}',
'\\boldsymbol{AaBb}',
'\\bot',
'\\bowtie',
'\\Box',
'\\boxdot',
'\\boxed{ab}',
'\\boxminus',
'\\boxplus',
'\\boxtimes',
'\\Bra{\\psi}',
'\\bra{\\psi}',
'\\braket{\\phi\\vert\\psi}',
'{n\\brace k}',
'\\bracevert',
'{n\\brack k}',
'\\breve{eu}',
'\\buildrel',
'\\bull',
'\\bullet',
'\\Bumpeq',
'\\bumpeq',
'\\C',
'\\cal AaBb123',
'\\cancel{5}',
'\\cancelto',
'\\Cap',
'\\cap',
'\\begin{cases}a&\\text{if }b\\\\c&\\text{if }d\\end{cases}',
'\\cases',
'\\begin{CD}A @>a>> B \\\\@VbVV @AAcA\\\\C @= D\\end{CD}',
'\\cdot',
'\\cdotp',
'\\cdots',
'{\\mathrm{C}{\\vphantom{X}}_{\\smash[t]{6}}\\mathrm{H}{\\vphantom{X}}_{\\smash[t]{5}}{-}\\mathrm{CHO}}',
'\\cee',
'a\\centerdot b',
'\\cf',
'use ',
'\\cfrac{2}{1+\\cfrac{2}{1+\\cfrac{2}{1}}}',
'\\char"263a',
'\\check{oe}',
'\\ch',
'\\checkmark',
'\\Chi',
'\\chi',
'{n+1 \\choose k+2}',
'\\circ',
'\\circeq',
'\\circlearrowleft',
'\\circlearrowright',
'\\circledast',
'\\circledcirc',
'\\circleddash',
'\\circledR',
'\\circledS',
'\\class',
'\\cline',
'\\clubs',
'\\clubsuit',
'\\cnums',
'\\colon',
'\\Colonapprox',
'\\colonapprox',
'\\coloncolon',
'\\coloncolonapprox',
'\\coloncolonequals',
'\\coloncolonminus',
'\\coloncolonsim',
'\\Coloneq',
'\\coloneq',
'\\colonequals',
'\\Coloneqq',
'\\coloneqq',
'\\colonminus',
'\\Colonsim',
'\\colonsim',
'\\color{#0000FF} AaBb123',
'\\colorbox{red}{Black on red}',
'\\complement',
'\\Complex',
'\\cong',
'\\Coppa',
'\\coppa',
'\\coprod',
'\\copyright',
'\\cos',
'\\cosec',
'\\cosh',
'\\cot',
'\\cotg',
'\\coth',
'\\begin{matrix} a & b\\cr c & d \\end{matrix}',
'\\csc',
'\\cssId',
'\\ctg',
'\\cth',
'\\Cup',
'\\cup',
'\\curlyeqprec',
'\\curlyeqsucc',
'\\curlyvee',
'\\curlywedge',
'\\curvearrowleft',
'\\curvearrowright',
'\\dag',
'\\Dagger',
'\\dagger',
'\\daleth',
'\\Darr',
'\\dArr',
'\\darr',
'\\begin{darray}{cc}a&b\\\\c&d\\end{darray}',
'\\dashleftarrow',
'\\dashrightarrow',
'\\dashv',
'\\dbinom n k',
'\\dblcolon',
'\\begin{dcases}a&\\text{if }b\\\\c&\\text{if }d\\end{dcases}',
'\\ddag',
'\\ddagger',
'\\ddddot',
'\\dddot',
'\\ddot x',
'\\ddots',
'\\DeclareMathOperator',
'\\def\\foo{x^2} \\foo + \\foo',
'\\definecolor',
'\\deg',
'\\degree',
'\\delta',
'\\Delta',
'\\det',
'\\Digamma',
'\\digamma',
'\\dfrac{a-1}{b-1}',
'\\diagdown',
'\\diagup',
'\\Diamond',
'\\diamond',
'\\diamonds',
'\\diamondsuit',
'\\dim',
'\\displaylines',
'\\displaystyle\\sum_0^n',
'\\div',
'\\divideontimes',
'\\dot x',
'\\Doteq',
'\\doteq',
'\\doteqdot',
'\\dotplus',
'x_1 + \\dots + x_n',
'x_1 +\\dotsb + x_n',
'x,\\dotsc,y',
'\\int_{A_1}\\int_{A_2}\\dotsi',
'x_1 x_2 \\dotsm x_n',
'\\dotso',
'\\doublebarwedge',
'\\doublecap',
'\\doublecup',
'\\Downarrow',
'\\downarrow',
'\\downdownarrows',
'\\downharpoonleft',
'\\downharpoonright',
'\\begin{drcases}a&\\text{if }b\\\\c&\\text{if }d\\end{drcases}',
'\\def\\foo{a}\\edef\\bar{\\foo}\\def\\foo{}\\bar',
'\\ell',
'\\else',
'\\em',
'\\emph',
'\\empty',
'\\emptyset',
'\\enclose',
'\\begin{matrix} a & b\\\\ c & d\\end{matrix}',
'\\endgroup',
'a\\enspace b',
'\\Epsilon',
'\\epsilon',
'\\eqalign',
'\\eqalignno',
'\\eqcirc',
'\\Eqcolon',
'\\eqcolon',
'\\begin{equation}a = b + c\\end{equation}',
'\\begin{equation*}a = b + c\\end{equation*}',
'{eqnarray}',
'\\Eqqcolon',
'\\eqqcolon',
'\\eqref',
'\\eqsim',
'\\eqslantgtr',
'\\eqslantless',
'\\equalscolon',
'\\equalscoloncolon',
'\\equiv',
'\\Eta',
'\\eta',
'\\eth',
'\\euro',
'\\exist',
'\\exists',
'\\exp',
'\\expandafter',
'\\fallingdotseq',
'\\fbox{Hi there!}',
'\\fcolorbox{red}{aqua}{A}',
'\\fi',
'\\Finv',
'\\flat',
'\\footnotesize footnotesize',
'\\forall',
'\\frac a b',
'\\frak{AaBb}',
'\\frown',
'\\futurelet',
'\\Game',
'\\Gamma',
'\\gamma',
'\\begin{gather}a=b\\\\e=b+c\\end{gather}',
'\\begin{gathered}a=b\\\\e=b+c\\end{gathered}',
'\\gcd',
'\\gdef\\bar#1{#1^2} \\bar{y} + \\bar{y}',
'\\ge',
'\\geneuro',
'\\geneuronarrow',
'\\geneurowide',
'\\genfrac ( ] {2pt}{0}a{a+1}',
'\\geq',
'\\geqq',
'\\geqslant',
'\\gets',
'\\gg',
'\\ggg',
'\\gggtr',
'\\gimel',
'\\global\\def\\add#1#2{#1+#2} \\add 2 3',
'\\gnapprox',
'\\gneq',
'\\gneqq',
'\\gnsim',
'\\grave{eu}',
'a \\gt b',
'\\gtrdot',
'\\gtrapprox',
'\\gtreqless',
'\\gtreqqless',
'\\gtrless',
'\\gtrsim',
'\\gvertneqq',
'\\text{\\H{a}}',
'\\Harr',
'\\hArr',
'\\harr',
'\\hat{\\theta}',
'\\hbar',
'\\hbox{$x^2$}',
'\\hbox to ',
'\\begin{matrix}a&b\\\\ \\hdashline c &d\\end{matrix}',
'\\hearts',
'\\heartsuit',
'\\hfil',
'\\hfill',
'\\begin{matrix}a&b\\\\ \\hline c &d\\end{matrix}',
'\\hom',
'\\hookleftarrow',
'\\hookrightarrow',
'a\\hphantom{bc}d',
'\\href{https://katex.org/}{\\KaTeX}',
'w\\hskip1em i\\hskip2em d',
'\\hslash',
's\\hspace7ex k',
'\\htmlClass{foo}{x}',
'\\htmlData{foo=a, bar=b}{x}',
'\\htmlId{bar}{x}',
'\\htmlStyle{color: red;}{x}',
'\\huge huge',
'\\Huge Huge',
'\\text{\\i}',
'\\idotsint',
'\\iddots',
'\\if',
'A\\iff B',
'\\ifmode',
'\\ifx',
'\\iiiint',
'\\iiint',
'\\iint',
'\\Im',
'\\image',
'\\imageof',
'\\imath',
'P\\impliedby Q',
'P\\implies Q',
'\\in',
'\\inf',
'\\infin',
'\\infty',
'\\injlim',
'\\int',
'\\intercal',
'\\intop',
'\\Iota',
'\\iota',
'\\isin',
'{\\it AaBb}',
'\\itshape',
'\\text{\\j}',
'\\jmath',
'\\Join',
'\\Kappa',
'\\kappa',
'\\KaTeX',
'\\ker',
'I\\kern-2.5pt R',
'\\Ket{\\psi}',
'\\ket{\\psi}',
'\\Koppa',
'\\koppa',
'\\L',
'\\l',
'\\Lambda',
'\\lambda',
'\\label',
'\\land',
'\\lang A\\rangle',
'\\langle A\\rangle',
'\\Larr',
'\\lArr',
'\\larr',
'\\large large',
'\\Large Large',
'\\LARGE LARGE',
'\\LaTeX',
'\\lBrace',
'\\lbrace',
'\\lbrack',
'\\lceil',
'\\ldotp',
'\\ldots',
'\\le',
'\\leadsto',
'\\left\\lbrace \\dfrac ab \\right.',
'\\leftarrow',
'\\Leftarrow',
'\\LeftArrow',
'\\leftarrowtail',
'\\leftharpoondown',
'\\leftharpoonup',
'\\leftleftarrows',
'\\Leftrightarrow',
'\\leftrightarrow',
'\\leftrightarrows',
'\\leftrightharpoons',
'\\leftrightsquigarrow',
'\\leftroot',
'\\leftthreetimes',
'\\leq',
'\\leqalignno',
'\\leqq',
'\\leqslant',
'\\lessapprox',
'\\lessdot',
'\\lesseqgtr',
'\\lesseqqgtr',
'\\lessgtr',
'\\lesssim',
'\\let',
'\\lfloor',
'\\lg',
'\\lgroup',
'\\lhd',
'\\lim',
'\\liminf',
'\\lim\\limits_x',
'\\limsup',
'\\ll',
'{=}\\llap{/\\,}',
'\\llbracket',
'\\llcorner',
'\\Lleftarrow',
'\\lll',
'\\llless',
'\\lmoustache',
'\\ln',
'\\lnapprox',
'\\lneq',
'\\lneqq',
'\\lnot',
'\\lnsim',
'\\log',
'\\long',
'\\Longleftarrow',
'\\longleftarrow',
'\\Longleftrightarrow',
'\\longleftrightarrow',
'\\longmapsto',
'\\Longrightarrow',
'\\longrightarrow',
'\\looparrowleft',
'\\looparrowright',
'\\lor',
'\\lower',
'\\lozenge',
'\\lparen',
'\\Lrarr',
'\\lrArr',
'\\lrarr',
'\\lrcorner',
'\\lq',
'\\Lsh',
'\\lt',
'\\ltimes',
'\\lVert',
'\\lvert',
'\\lvertneqq',
'\\maltese',
'\\mapsto',
'\\mathbb{AB}',
'\\mathbf{AaBb123}',
'a\\mathbin{!}b',
'\\mathcal{AaBb123}',
'a\\mathchoice{\\,}{\\,\\,}{\\,\\,\\,}{\\,\\,\\,\\,}b',
'\\displaystyle\\sum_{\\mathclap{1\\le i\\le n}} x_{i}',
'a + (b\\mathclose\\gt + c',
'\\mathellipsis',
'\\mathfrak{AaBb}',
'ab\\mathinner{\\text{inside}}cd',
'\\mathit{AaBb}',
'{=}\\mathllap{/\\,}',
'\\mathnormal{AaBb}',
'\\mathop{\\star}_a^b',
'a + \\mathopen\\lt b) + c',
'1\\mathord{,}234{,}567',
'A\\mathpunct{-}B',
'a \\mathrel{\\#} b',
'\\mathrlap{\\,/}{=}',
'\\mathring{a}',
'\\mathrm{AaBb123}',
'\\mathscr{AB}',
'\\mathsf{AaBb123}',
'\\mathsterling',
'\\sqrt{\\mathstrut a}',
'\\mathtip',
'\\mathtt{AaBb123}',
'\\matrix',
'\\begin{matrix}a&b\\\\c&d\\end{matrix}',
'\\begin{matrix*}[r]0&-1\\\\-1&0\\end{matrix*}',
'\\max',
'\\mbox',
'\\md',
'\\mdseries',
'\\measuredangle',
'a\\medspace b',
'\\mho',
'\\{x∈ℝ\\mid x>0\\}',
'P\\left(A\\middle\\vert B\\right)',
'\\min',
'\\minuscolon',
'\\minuscoloncolon',
'\\minuso',
'\\mit',
'a\\mkern18mu b',
'\\mmlToken',
'3\\equiv 5 \\mod 2',
'\\models',
'\\moveleft',
'\\moveright',
'\\mp',
'a\\mskip{10mu}b',
'\\mspace',
'\\Mu',
'\\mu',
'\\multicolumn',
'{multiline}',
'\\multimap',
'\\N',
'\\nabla',
'\\natnums',
'\\natural',
'a\\negmedspace b',
'\\ncong',
'\\ne',
'\\nearrow',
'\\neg',
'a\\negthickspace b',
'a\\negthinspace b',
'\\neq',
'\\newcommand\\chk{\\checkmark} \\chk',
'\\newenvironment',
'\\Newextarrow',
'a\\newline b',
'\\nexists',
'\\ngeq',
'\\ngeqq',
'\\ngeqslant',
'\\ngtr',
'\\ni',
'\\nleftarrow',
'\\nLeftarrow',
'\\nLeftrightarrow',
'\\nleftrightarrow',
'\\nleq',
'\\nleqq',
'\\nleqslant',
'\\nless',
'\\nmid',
'\\nobreak',
'a\\nobreakspace b',
'\\noexpand',
'\\lim\\nolimits_x',
'\\normalfont',
'\\normalsize normalsize',
'\\not =',
'\\notag',
'\\notin',
'\\notni',
'\\nparallel',
'\\nprec',
'\\npreceq',
'\\nRightarrow',
'\\nrightarrow',
'\\nshortmid',
'\\nshortparallel',
'\\nsim',
'\\nsubseteq',
'\\nsubseteqq',
'\\nsucc',
'\\nsucceq',
'\\nsupseteq',
'\\nsupseteqq',
'\\ntriangleleft',
'\\ntrianglelefteq',
'\\ntriangleright',
'\\ntrianglerighteq',
'\\Nu',
'\\nu',
'\\nVDash',
'\\nVdash',
'\\nvDash',
'\\nvdash',
'\\nwarrow',
'\\text{\\O}',
'\\text{\\o}',
'\\odot',
'\\text{\\OE}',
'\\text{\\oe}',
'\\officialeuro',
'\\oiiint',
'\\oiint',
'\\oint',
'\\oldstyle',
'\\omega',
'\\Omega',
'\\Omicron',
'\\omicron',
'\\ominus',
'\\operatorname{asin} x',
'\\operatorname*{asin}\\limits_y x',
'\\operatornamewithlimits{asin}\\limits_y x',
'\\oplus',
'\\or',
'\\origof',
'\\oslash',
'\\otimes',
'{a+1 \\over b+2}+c',
'\\overbrace{x+⋯+x}^{n\\text{ times}}',
'\\overbracket',
'\\overgroup{AB}',
'\\overleftarrow{AB}',
'\\overleftharpoon{AB}',
'\\overleftrightarrow{AB}',
'\\overline{\\text{a long argument}}',
'\\overlinesegment{AB}',
'\\overparen',
'\\Overrightarrow{AB}',
'\\overrightarrow{AB}',
'\\overrightharpoon{ac}',
'\\overset{!}{=}',
'\\overwithdelims',
'\\owns',
'\\text{\\P}',
'\\pagecolor',
'\\parallel',
'\\part',
'\\partial',
'\\perp',
'\\Gamma^{\\phantom{i}j}_{i\\phantom{j}k}',
'\\phase{-78^\\circ}',
'\\Phi',
'\\phi',
'\\Pi',
'\\pi',
'{picture}',
'\\pitchfork',
'\\plim',
'\\plusmn',
'\\pm',
'\\pmatrix',
'\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}',
'\\begin{pmatrix*}[r]0&-1\\\\-1&0\\end{pmatrix*}',
'\\pmb{\\mu}',
'x\\pmod a',
'x \\pod a',
'\\pounds',
'\\Pr',
'\\prec',
'\\precapprox',
'\\preccurlyeq',
'\\preceq',
'\\precnapprox',
'\\precneqq',
'\\precnsim',
'\\precsim',
'\\prime',
'\\prod',
'\\projlim',
'\\propto',
'\\providecommand\\greet{\\text{Hello}} \\greet',
'\\psi',
'\\Psi',
'{123~\\mathchoice{\\textstyle\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}{\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}{\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}{\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}}',
'\\Q',
'a\\qquad\\qquad{b}',
'a\\quad\\quad{b}',
'\\R',
'\\text{\\r{a}}',
'\\raise',
'h\\raisebox{2pt}{ighe}r',
'\\langle A\\rang',
'\\langle A\\rangle',
'\\Rarr',
'\\rArr',
'\\rarr',
'\\ratio',
'\\rBrace',
'\\rbrace',
'\\rbrack',
'\\begin{rcases}a&\\text{if }b\\\\c&\\text{if }d\\end{rcases}',
'\\rceil',
'\\Re',
'\\real',
'\\Reals',
'\\reals',
'\\ref',
'\\relax',
'\\def\\hail{Hi!}\\renewcommand\\hail{\\text{Ahoy!}} \\hail',
'\\renewenvironment',
'\\require',
'\\restriction',
'\\rfloor',
'\\rgroup',
'\\rhd',
'\\Rho',
'\\rho',
'\\left.\\dfrac a b\\right)',
'\\Rightarrow',
'\\rightarrow',
'\\rightarrowtail',
'\\rightharpoondown',
'\\rightharpoonup',
'\\rightleftarrows',
'\\rightleftharpoons',
'\\rightrightarrows',
'\\rightsquigarrow',
'\\rightthreetimes',
'\\risingdotseq',
'\\rlap{\\,/}{=}',
'\\rm AaBb12',
'\\rmoustache',
'\\root',
'\\rotatebox',
'\\rparen',
'\\rq',
'\\rrbracket',
'\\Rrightarrow',
'\\Rsh',
'\\rtimes',
'\\Rule',
'x\\rule[6pt]{2ex}{1ex}x',
'\\rVert',
'\\rvert',
'\\text{\\S}',
'\\Sampi',
'\\sampi',
'\\sc',
'\\scalebox',
'\\scr',
'\\scriptscriptstyle \\frac cd',
'\\scriptsize scriptsize',
'\\frac ab + {\\scriptstyle \\frac cd}',
'\\sdot',
'\\searrow',
'\\sec',
'\\text{\\sect}',
'\\setlength',
'\\setminus',
'\\sf AaBb123',
'\\sharp',
'\\shortmid',
'\\shortparallel',
'\\shoveleft',
'\\shoveright',
'\\sideset',
'\\Sigma',
'\\sigma',
'\\sim',
'\\simcolon',
'\\simcoloncolon',
'\\simeq',
'\\sin',
'\\sinh',
'\\sixptsize sixptsize',
'\\sh',
'\\skew',
'\\skip',
'\\sl',
'\\small small',
'\\smallfrown',
'\\smallint',
'\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}',
'\\smallsetminus',
'\\smallsmile',
'\\left(x^{\\smash{2}}\\right)',
'\\smile',
'\\smiley',
'\\sout{abc}',
'\\Space',
'a\\space b',
'\\spades',
'\\spadesuit',
'\\sphericalangle',
'\\begin{equation}\\begin{split}a &=b+c\\\\&=e+f\\end{split}\\end{equation}',
'\\sqcap',
'\\sqcup',
'\\square',
'\\sqrt[3]{x}',
'\\sqsubset',
'\\sqsubseteq',
'\\sqsupset',
'\\sqsupseteq',
'\\text{\\ss}',
'\\stackrel{!}{=}',
'\\star',
'\\Stigma',
'\\stigma',
'\\strut',
'\\style',
'\\sub',
'{subarray}',
'\\sube',
'\\Subset',
'\\subset',
'\\subseteq',
'\\subseteqq',
'\\subsetneq',
'\\subsetneqq',
'\\sum_{\\substack{0<i<m\\\\0<j<n}}',
'\\succ',
'\\succapprox',
'\\succcurlyeq',
'\\succeq',
'\\succnapprox',
'\\succneqq',
'\\succnsim',
'\\succsim',
'\\sum',
'\\sup',
'\\supe',
'\\Supset',
'\\supset',
'\\supseteq',
'\\supseteqq',
'\\supsetneq',
'\\supsetneqq',
'\\surd',
'\\swarrow',
'\\tag{3.1c} a^2+b^2=c^2',
'\\tag*{3.1c} a^2+b^2=c^2',
'\\tan',
'\\tanh',
'\\Tau',
'\\tau',
'\\tbinom n k',
'\\TeX',
'\\text{ yes }\\&\\text{ no }',
'\\text{\\textasciitilde}',
'\\text{\\textasciicircum}',
'\\text{\\textbackslash}',
'\\text{\\textbar}',
'\\text{\\textbardbl}',
'\\textbf{AaBb123}',
'\\text{\\textbraceleft}',
'\\text{\\textbraceright}',
'\\text{\\textcircled a}',
'\\textcolor{blue}{F=ma}',
'\\text{\\textdagger}',
'\\text{\\textdaggerdbl}',
'\\text{\\textdegree}',
'\\text{\\textdollar}',
'\\text{\\textellipsis}',
'\\text{\\textemdash}',
'\\text{\\textendash}',
'\\text{\\textgreater}',
'\\textit{AaBb}',
'\\text{\\textless}',
'\\textmd{AaBb123}',
'\\textnormal{AB}',
'\\text{\\textquotedblleft}',
'\\text{\\textquotedblright}',
'\\text{\\textquoteleft}',
'\\text{\\textquoteright}',
'\\text{\\textregistered}',
'\\textrm{AaBb123}',
'\\textsc',
'\\textsf{AaBb123}',
'\\textsl',
'\\text{\\textsterling}',
'\\textstyle\\sum_0^n',
'\\texttip',
'\\texttt{AaBb123}',
'\\text{\\textunderscore}',
'\\textup{AaBb123}',
'\\textvisiblespace',
'\\tfrac ab',
'\\tg',
'\\th',
'\\therefore',
'\\Theta',
'\\theta',
'\\thetasym',
'\\thickapprox',
'\\thicksim',
'a\\thickspace b',
'a\\thinspace b',
'\\tilde M',
'\\times',
'\\Tiny',
'\\tiny tiny',
'\\to',
'\\toggle',
'\\top',
'\\triangle',
'\\triangledown',
'\\triangleleft',
'\\trianglelefteq',
'\\triangleq',
'\\triangleright',
'\\trianglerighteq',
'{\\tt AaBb123}',
'\\twoheadleftarrow',
'\\twoheadrightarrow',
'\\text{\\u{a}}',
'\\Uarr',
'\\uArr',
'\\uarr',
'\\ulcorner',
'\\underbar{X}',
'\\underbrace{x+⋯+x}_{n\\text{ times}}',
'\\underbracket',
'\\undergroup{AB}',
'\\underleftarrow{AB}',
'\\underleftrightarrow{AB}',
'\\underrightarrow{AB}',
'\\underline{\\text{a long argument}}',
'\\underlinesegment{AB}',
'\\underparen',
'\\underrightarrow{AB}',
'\\underset{!}{=}',
'\\unicode',
'\\unlhd',
'\\unrhd',
'\\up',
'\\Uparrow',
'\\uparrow',
'\\Updownarrow',
'\\updownarrow',
'\\upharpoonleft',
'\\upharpoonright',
'\\uplus',
'\\uproot',
'\\upshape',
'\\Upsilon',
'\\upsilon',
'\\upuparrows',
'\\urcorner',
'\\footnotesize\\url{https://katex.org/}',
'\\utilde{AB}',
'\\text{\\v{a}}',
'\\varcoppa',
'\\varDelta',
'\\varepsilon',
'\\varGamma',
'\\varinjlim',
'\\varkappa',
'\\varLambda',
'\\varliminf',
'\\varlimsup',
'\\varnothing',
'\\varOmega',
'\\varPhi',
'\\varphi',
'\\varPi',
'\\varpi',
'\\varprojlim',
'\\varpropto',
'\\varPsi',
'\\varPsi',
'\\varrho',
'\\varSigma',
'\\varsigma',
'\\varstigma',
'\\varsubsetneq',
'\\varsubsetneqq',
'\\varsupsetneq',
'\\varsupsetneqq',
'\\varTheta',
'\\vartheta',
'\\vartriangle',
'\\vartriangleleft',
'\\vartriangleright',
'\\varUpsilon',
'\\varXi',
'\\mathrel{\\vcentcolon =}',
'a+\\left(\\vcenter{\\frac{\\frac a b}c}\\right)',
'a+\\left(\\vcenter{\\frac{\\frac a b}c}\\right)',
'\\Vdash',
'\\vDash',
'\\vdash',
'\\vdots',
'\\vec{F}',
'\\vee',
'\\veebar',
'\\verb!\\frac a b!',
'\\Vert',
'\\vert',
'\\vfil',
'\\vfill',
'\\vline',
'\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}',
'\\begin{Vmatrix*}[r]0&-1\\\\-1&0\\end{Vmatrix*}',
'\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}',
'\\begin{vmatrix*}[r]0&-1\\\\-1&0\\end{vmatrix*}',
'\\overline{\\vphantom{M}a}',
'\\Vvdash',
'\\wedge',
'\\weierp',
'\\widecheck{AB}',
'\\widehat{AB}',
'\\wideparen',
'\\widetilde{AB}',
'\\wp',
'\\wr',
'\\xcancel{ABC}',
'\\def\\foo{a}\\xdef\\bar{\\foo}\\def\\foo{}\\bar',
'\\Xi',
'\\xi',
'\\xhookleftarrow{abc}',
'\\xhookrightarrow{abc}',
'\\xLeftarrow{abc}',
'\\xleftarrow{abc}',
'\\xleftharpoondown{abc}',
'\\xleftharpoonup{abc}',
'\\xLeftrightarrow{abc}',
'\\xleftrightarrow{abc}',
'\\xleftrightharpoons{abc}',
'\\xlongequal{abc}',
'\\xmapsto{abc}',
'\\xRightarrow{abc}',
'\\xrightarrow{abc}',
'\\xrightharpoondown{abc}',
'\\xrightharpoonup{abc}',
'\\xrightleftharpoons{abc}',
'\\xtofrom{abc}',
'\\xtwoheadleftarrow{abc}',
'\\xtwoheadrightarrow{abc}',
'\\yen',
'\\Z',
'\\Zeta',
'\\zeta'
}

output = {}
for i,w in ipairs(commands) do
  output[i] = {word = w; label = w; insertText = w; filterText = w}
end
return output
